// Code generated by goplus from gosmt.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package gosmt exposes Z3-shaped, context-indexed solver construction over
// the essential Go+ standard-library SMT core.
package gosmt

import (
	smt "goforge.dev/goplus/std/smt"
	"goforge.dev/goplus/std/smtlib"
)

//goplus:enum Context[c nat]
//goplus:derive off
//goplus:repr transparent
type Context = contextValue

//goplus:variant (Context) contextValue(ID int) Context[c]
type contextValue struct {
	iD int
}

func (contextValue) isContext() {}

// Expressions from different contexts cannot be composed in Go+.
//
//goplus:enum BoolExpr[c nat]
//goplus:derive off
//goplus:repr transparent
type BoolExpr = boolExprValue

//goplus:variant (BoolExpr) boolExprValue(ContextID int, Term smt.Term[smt.BoolSort], Fast booleanFast) BoolExpr[c]
type boolExprValue struct {
	contextID int
	term      smt.Term[smt.BoolSort]
	fast      booleanFast
}

func (boolExprValue) isBoolExpr() {}

//goplus:enum IntExpr[c nat]
//goplus:derive off
//goplus:repr transparent
type IntExpr = intExprValue

//goplus:variant (IntExpr) intExprValue(ContextID int, Term smt.Term[smt.IntSort]) IntExpr[c]
type intExprValue struct {
	contextID int
	term      smt.Term[smt.IntSort]
}

func (intExprValue) isIntExpr() {}

//goplus:enum RealExpr[c nat]
//goplus:derive off
//goplus:repr transparent
type RealExpr = realExprValue

//goplus:variant (RealExpr) realExprValue(ContextID int, Term smt.Term[smt.RealSort], Fast realFast) RealExpr[c]
type realExprValue struct {
	contextID int
	term      smt.Term[smt.RealSort]
	fast      realFast
}

func (realExprValue) isRealExpr() {}

//goplus:enum BitVecExpr[c nat, w nat]
//goplus:derive off
//goplus:repr transparent
type BitVecExpr = bitVecExprValue

//goplus:variant (BitVecExpr) bitVecExprValue(ContextID int, Term smt.Term[smt.BitVecSort[w]], Fast bitVectorFast) BitVecExpr[c, w]
type bitVecExprValue struct {
	contextID int
	term      smt.Term[smt.BitVecSort]
	fast      bitVectorFast
}

func (bitVecExprValue) isBitVecExpr() {}

//goplus:enum ArrayExpr[c nat, I any, E any]
//goplus:derive off
type ArrayExpr[I any, E any] interface{ isArrayExpr(I, E) }

//goplus:variant (ArrayExpr[I, E]) arrayExprValue(ContextID int, Term smt.Term[smt.ArraySort[I, E]], Fast arrayFast) ArrayExpr[c, I, E]
type arrayExprValue[I any, E any] struct {
	contextID int
	term      smt.Term[smt.ArraySort[I, E]]
	fast      arrayFast
}

func (arrayExprValue[I, E]) isArrayExpr(I, E) {}

//goplus:enum BitVecArrayExpr[c nat, iw nat, ew nat]
//goplus:derive off
//goplus:repr transparent
type BitVecArrayExpr = bitVecArrayExprValue

//goplus:variant (BitVecArrayExpr) bitVecArrayExprValue(ContextID int, Term smt.Term[smt.ArraySort[smt.BitVecSort[iw], smt.BitVecSort[ew]]], Fast bitVecArrayFast) BitVecArrayExpr[c, iw, ew]
type bitVecArrayExprValue struct {
	contextID int
	term      smt.Term[smt.ArraySort[smt.BitVecSort, smt.BitVecSort]]
	fast      bitVecArrayFast
}

func (bitVecArrayExprValue) isBitVecArrayExpr() {}

//goplus:enum UninterpretedExpr[c nat, s nat]
//goplus:derive off
//goplus:repr transparent
type UninterpretedExpr = uninterpretedExprValue

//goplus:variant (UninterpretedExpr) uninterpretedExprValue(ContextID int, Term smt.Term[smt.UninterpretedSort[s]]) UninterpretedExpr[c, s]
type uninterpretedExprValue struct {
	contextID int
	term      smt.Term[smt.UninterpretedSort]
}

func (uninterpretedExprValue) isUninterpretedExpr() {}

//goplus:enum UnaryFunc[c nat, d nat, r nat]
//goplus:derive off
//goplus:repr transparent
type UnaryFunc = unaryFuncValue

//goplus:variant (UnaryFunc) unaryFuncValue(ContextID int, Function smt.UnaryFunction[d, r]) UnaryFunc[c, d, r]
type unaryFuncValue struct {
	contextID int
	function  smt.UnaryFunction
}

func (unaryFuncValue) isUnaryFunc() {}

//goplus:enum BinaryFunc[c nat, a nat, b nat, r nat]
//goplus:derive off
//goplus:repr transparent
type BinaryFunc = binaryFuncValue

//goplus:variant (BinaryFunc) binaryFuncValue(ContextID int, Function smt.BinaryFunction[a, b, r]) BinaryFunc[c, a, b, r]
type binaryFuncValue struct {
	contextID int
	function  smt.BinaryFunction
}

func (binaryFuncValue) isBinaryFunc() {}

//goplus:enum RealFunc[c nat]
//goplus:derive off
//goplus:repr transparent
type RealFunc = realFuncValue

//goplus:variant (RealFunc) realFuncValue(ContextID int, Function smt.SortedUnaryFunction[smt.RealSort, smt.RealSort], Fast realFunctionFast) RealFunc[c]
type realFuncValue struct {
	contextID int
	function  smt.SortedUnaryFunction[smt.RealSort, smt.RealSort]
	fast      realFunctionFast
}

func (realFuncValue) isRealFunc() {}

//goplus:enum RealBinaryFunc[c nat]
//goplus:derive off
//goplus:repr transparent
type RealBinaryFunc = realBinaryFuncValue

//goplus:variant (RealBinaryFunc) realBinaryFuncValue(ContextID int, Function smt.SortedBinaryFunction[smt.RealSort, smt.RealSort, smt.RealSort], Fast realBinaryFunctionFast) RealBinaryFunc[c]
type realBinaryFuncValue struct {
	contextID int
	function  smt.SortedBinaryFunction[smt.RealSort, smt.RealSort, smt.RealSort]
	fast      realBinaryFunctionFast
}

func (realBinaryFuncValue) isRealBinaryFunc() {}

//goplus:enum BitVecFunc[c nat, d nat, r nat]
//goplus:derive off
//goplus:repr transparent
type BitVecFunc = bitVecFuncValue

//goplus:variant (BitVecFunc) bitVecFuncValue(ContextID int, Function smt.SortedUnaryFunction[smt.BitVecSort[d], smt.BitVecSort[r]]) BitVecFunc[c, d, r]
type bitVecFuncValue struct {
	contextID int
	function  smt.SortedUnaryFunction[smt.BitVecSort, smt.BitVecSort]
}

func (bitVecFuncValue) isBitVecFunc() {}

//goplus:enum BitVecBinaryFunc[c nat, a nat, b nat, r nat]
//goplus:derive off
//goplus:repr transparent
type BitVecBinaryFunc = bitVecBinaryFuncValue

//goplus:variant (BitVecBinaryFunc) bitVecBinaryFuncValue(ContextID int, Function smt.SortedBinaryFunction[smt.BitVecSort[a], smt.BitVecSort[b], smt.BitVecSort[r]]) BitVecBinaryFunc[c, a, b, r]
type bitVecBinaryFuncValue struct {
	contextID int
	function  smt.SortedBinaryFunction[smt.BitVecSort, smt.BitVecSort, smt.BitVecSort]
}

func (bitVecBinaryFuncValue) isBitVecBinaryFunc() {}

//goplus:enum Solver[c nat, a nat, d nat]
//goplus:derive off
//goplus:repr transparent
type Solver = solverValue

//goplus:variant (Solver) solverValue(ContextID int, Core smt.Solver[a, d]) Solver[c, a, d]
type solverValue struct {
	contextID int
	core      smt.Solver
}

func (solverValue) isSolver() {}

//goplus:enum Model[c nat, a nat]
//goplus:derive off
//goplus:repr transparent
type Model = modelValue

//goplus:variant (Model) modelValue(ContextID int, Core smt.Model[a]) Model[c, a]
type modelValue struct {
	contextID int
	core      smt.Model
}

func (modelValue) isModel() {}

//goplus:enum Result[c nat, a nat]
type Result interface{ isResult() }

//goplus:variant (Result) Sat(Value Model[c, a])
type Sat struct {
	Value Model
}

func (Sat) isResult() {}

//goplus:variant (Result) Unsat(Context Context[c], Proof smt.Proof[a])
type Unsat struct {
	Context Context
	Proof   smt.Proof
}

func (Unsat) isResult() {}

//goplus:variant (Result) Unknown(Context Context[c], Proof smt.Proof[a], Reason smt.UnknownReason)
type Unknown struct {
	Context Context
	Proof   smt.Proof
	Reason  smt.UnknownReason
}

func (Unknown) isResult() {}

// ResultCases selects one handler per Result variant for ResultFold.
type ResultCases[R any] struct {
	Sat     func(Value Model) R
	Unsat   func(Context Context, Proof smt.Proof) R
	Unknown func(Context Context, Proof smt.Proof, Reason smt.UnknownReason) R
}

// ResultFold reduces Result by one-level case analysis.
func ResultFold[R any](v Result, cs ResultCases[R]) R {
	switch m := any(v).(type) {
	case Sat:
		return cs.Sat(m.Value)
	case Unsat:
		return cs.Unsat(m.Context, m.Proof)
	case Unknown:
		return cs.Unknown(m.Context, m.Proof, m.Reason)
	default:
		panic("goplus: impossible enum value in ResultFold")
	}
}

//goplus:enum AssumptionResult[c nat, a nat]
type AssumptionResult interface{ isAssumptionResult() }

//goplus:variant (AssumptionResult) AssumptionSat(Value Model[c, a])
type AssumptionSat struct {
	Value Model
}

func (AssumptionSat) isAssumptionResult() {}

//goplus:variant (AssumptionResult) AssumptionUnsat(Context Context[c], Proof smt.Proof[a], Indices []int)
type AssumptionUnsat struct {
	Context Context
	Proof   smt.Proof
	Indices []int
}

func (AssumptionUnsat) isAssumptionResult() {}

//goplus:variant (AssumptionResult) AssumptionUnknown(Context Context[c], Proof smt.Proof[a], Reason smt.UnknownReason)
type AssumptionUnknown struct {
	Context Context
	Proof   smt.Proof
	Reason  smt.UnknownReason
}

func (AssumptionUnknown) isAssumptionResult() {}

// AssumptionResultCases selects one handler per AssumptionResult variant for AssumptionResultFold.
type AssumptionResultCases[R any] struct {
	AssumptionSat     func(Value Model) R
	AssumptionUnsat   func(Context Context, Proof smt.Proof, Indices []int) R
	AssumptionUnknown func(Context Context, Proof smt.Proof, Reason smt.UnknownReason) R
}

// AssumptionResultFold reduces AssumptionResult by one-level case analysis.
func AssumptionResultFold[R any](a AssumptionResult, cs AssumptionResultCases[R]) R {
	switch m := any(a).(type) {
	case AssumptionSat:
		return cs.AssumptionSat(m.Value)
	case AssumptionUnsat:
		return cs.AssumptionUnsat(m.Context, m.Proof, m.Indices)
	case AssumptionUnknown:
		return cs.AssumptionUnknown(m.Context, m.Proof, m.Reason)
	default:
		panic("goplus: impossible enum value in AssumptionResultFold")
	}
}

func ParseSMTLib(source string) smtlib.ParseResult       { return smtlib.Parse(source) }
func ExecuteSMTLib(source string) smtlib.ExecutionResult { return smtlib.Execute(source) }

//goplus:dep NewContext(id nat) Context[id]
func NewContext(id int) Context {
	if id < 0 {
		panic("gosmt: negative context identity")
	}
	return contextValue{iD: int(id)}
}

//goplus:dep BoolConst(0 c nat, context Context[c], name string, id int) BoolExpr[c]
func BoolConst(context Context, name string, id int) BoolExpr {
	switch __gp_m0 := any(context).(type) {
	case contextValue:
		contextID := __gp_m0.iD

		if id >= 0 {
			return fastBooleanVariable(contextID, id)
		}
		return boolExprValue{contextID: contextID, term: smt.BoolSymbol{ID: id, Name: name}, fast: booleanFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BoolValue(0 c nat, context Context[c], value bool) BoolExpr[c]
func BoolValue(context Context, value bool) BoolExpr {
	switch __gp_m1 := any(context).(type) {
	case contextValue:
		contextID := __gp_m1.iD
		return boolExprValue{contextID: contextID, term: smt.Bool{Value: value}, fast: booleanFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep IntConst(0 c nat, context Context[c], name string, id int) IntExpr[c]
func IntConst(context Context, name string, id int) IntExpr {
	switch __gp_m2 := any(context).(type) {
	case contextValue:
		contextID := __gp_m2.iD
		return intExprValue{contextID: contextID, term: smt.IntegerVariable(id)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep IntVal(0 c nat, context Context[c], value int64) IntExpr[c]
func IntVal(context Context, value int64) IntExpr {
	switch __gp_m3 := any(context).(type) {
	case contextValue:
		contextID := __gp_m3.iD
		return intExprValue{contextID: contextID, term: smt.Integer{Value: value}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ParseInteger(value string) (smt.IntegerValue, error) { return smt.ParseIntegerValue(value) }

//goplus:dep IntValExact(0 c nat, context Context[c], value smt.IntegerValue) IntExpr[c]
func IntValExact(context Context, value smt.IntegerValue) IntExpr {
	switch __gp_m4 := any(context).(type) {
	case contextValue:
		contextID := __gp_m4.iD
		return intExprValue{contextID: contextID, term: smt.IntegerTerm(value)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func Rational(numerator int64, denominator int64) smt.Rational {
	return smt.NewRational(numerator, denominator)
}
func ParseRational(value string) (smt.Rational, error) { return smt.ParseRational(value) }
func CompareRational(left smt.Rational, right smt.Rational) int {
	return smt.CompareRational(left, right)
}

//goplus:dep RealConst(0 c nat, context Context[c], name string, id int) RealExpr[c]
func RealConst(context Context, name string, id int) RealExpr {
	switch __gp_m5 := any(context).(type) {
	case contextValue:
		contextID := __gp_m5.iD
		return fastRealSymbol(contextID, id)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep RealVal(0 c nat, context Context[c], value smt.Rational) RealExpr[c]
func RealVal(context Context, value smt.Rational) RealExpr {
	switch __gp_m6 := any(context).(type) {
	case contextValue:
		contextID := __gp_m6.iD
		return fastRealValue(contextID, value)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BitVecValue(width nat, 0 c nat, context Context[c], value uint64) BitVecExpr[c, width]
func BitVecValue(width int, context Context, value uint64) BitVecExpr {
	switch __gp_m7 := any(context).(type) {
	case contextValue:
		contextID := __gp_m7.iD
		return fastBitVectorValue(contextID, int(width), value)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BitVecConst(width nat, 0 c nat, context Context[c], name string, id int) BitVecExpr[c, width]
func BitVecConst(width int, context Context, name string, id int) BitVecExpr {
	switch __gp_m8 := any(context).(type) {
	case contextValue:
		contextID := __gp_m8.iD
		return fastBitVectorSymbol(contextID, int(width), id, name)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// BvToNat interprets a bit vector as an unsigned mathematical integer.
//
//goplus:dep BvToNat(0 c nat, 0 width nat, value BitVecExpr[c, width]) IntExpr[c]
func BvToNat(value BitVecExpr) IntExpr {
	switch __gp_m9 := any(value).(type) {
	case bitVecExprValue:
		contextID := __gp_m9.contextID
		term := __gp_m9.term
		fast := __gp_m9.fast

		return intExprValue{contextID: contextID, term: smt.BitVecToNat(materializeBitVector(term, fast))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// BvToInt interprets a bit vector using two's-complement signed semantics.
//
//goplus:dep BvToInt(0 c nat, 0 width nat, value BitVecExpr[c, width]) IntExpr[c]
func BvToInt(value BitVecExpr) IntExpr {
	switch __gp_m10 := any(value).(type) {
	case bitVecExprValue:
		contextID := __gp_m10.contextID
		term := __gp_m10.term
		fast := __gp_m10.fast

		return intExprValue{contextID: contextID, term: smt.BitVecToInt(materializeBitVector(term, fast))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// IntToBitVec reduces an integer modulo 2^width. Its result width remains a
// dependent index, so mismatched widths are rejected by Go+ at compile time.
//
//goplus:dep IntToBitVec(width nat, 0 c nat, value IntExpr[c]) BitVecExpr[c, width]
func IntToBitVec(width int, value IntExpr) BitVecExpr {
	switch __gp_m11 := any(value).(type) {
	case intExprValue:
		contextID := __gp_m11.contextID
		term := __gp_m11.term

		return bitVecExprValue{contextID: contextID, term: smt.IntToBitVec(width, term), fast: bitVectorFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ArrayConst[I any, E any](0 c nat, context Context[c], name string, id int) ArrayExpr[c, I, E]
func ArrayConst[I any, E any](context Context, name string, id int) ArrayExpr[I, E] {
	switch __gp_m12 := any(context).(type) {
	case contextValue:
		contextID := __gp_m12.iD
		return arrayExprValue[I, E]{contextID: contextID, term: smt.ArrayConst[I, E](id, name), fast: arrayFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ConstArray[I any, E any](0 c nat, context Context[c], value smt.Term[E]) ArrayExpr[c, I, E]
func ConstArray[I any, E any](context Context, value smt.Term[E]) ArrayExpr[I, E] {
	switch __gp_m13 := any(context).(type) {
	case contextValue:
		contextID := __gp_m13.iD
		return arrayExprValue[I, E]{contextID: contextID, term: smt.ConstArray[I, E](value), fast: arrayFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep SelectArray[I any, E any](0 c nat, array ArrayExpr[c, I, E], index smt.Term[I]) smt.Term[E]
func SelectArray[I any, E any](array ArrayExpr[I, E], index smt.Term[I]) smt.Term[E] {
	switch __gp_m14 := any(array).(type) {
	case arrayExprValue[I, E]:
		term := __gp_m14.term
		fast := __gp_m14.fast
		return smt.Select(materializeArray(term, fast), index)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep StoreArray[I any, E any](0 c nat, array ArrayExpr[c, I, E], index smt.Term[I], value smt.Term[E]) ArrayExpr[c, I, E]
func StoreArray[I any, E any](array ArrayExpr[I, E], index smt.Term[I], value smt.Term[E]) ArrayExpr[I, E] {
	switch __gp_m15 := any(array).(type) {
	case arrayExprValue[I, E]:
		contextID := __gp_m15.contextID
		term := __gp_m15.term
		fast := __gp_m15.fast
		return arrayExprValue[I, E]{contextID: contextID, term: smt.Store(materializeArray(term, fast), index, value), fast: arrayFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EqArray[I any, E any](0 c nat, left ArrayExpr[c, I, E], right ArrayExpr[c, I, E]) BoolExpr[c]
func EqArray[I any, E any](left ArrayExpr[I, E], right ArrayExpr[I, E]) BoolExpr {
	switch __gp_m16 := any(left).(type) {
	case arrayExprValue[I, E]:
		contextID := __gp_m16.contextID
		leftTerm := __gp_m16.term
		leftFast := __gp_m16.fast

		switch __gp_m17 := any(right).(type) {
		case arrayExprValue[I, E]:
			rightContext := __gp_m17.contextID
			rightTerm := __gp_m17.term
			rightFast := __gp_m17.fast

			if contextID != rightContext {
				panic("gosmt: erased array context mismatch")
			}
			return fastEqArray(contextID, leftTerm, leftFast, rightTerm, rightFast)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep IntArrayConst(0 c nat, context Context[c], name string, id int) ArrayExpr[c, smt.IntSort, smt.IntSort]
func IntArrayConst(context Context, name string, id int) ArrayExpr[smt.IntSort, smt.IntSort] {
	switch __gp_m18 := any(context).(type) {
	case contextValue:
		contextID := __gp_m18.iD
		return fastIntArraySymbol(contextID, id, name)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ConstIntArray(0 c nat, value IntExpr[c]) ArrayExpr[c, smt.IntSort, smt.IntSort]
func ConstIntArray(value IntExpr) ArrayExpr[smt.IntSort, smt.IntSort] {
	switch __gp_m19 := any(value).(type) {
	case intExprValue:
		contextID := __gp_m19.contextID
		term := __gp_m19.term
		return fastConstIntArray(contextID, term)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep SelectIntArray(0 c nat, array ArrayExpr[c, smt.IntSort, smt.IntSort], index IntExpr[c]) IntExpr[c]
func SelectIntArray(array ArrayExpr[smt.IntSort, smt.IntSort], index IntExpr) IntExpr {
	switch __gp_m20 := any(array).(type) {
	case arrayExprValue[smt.IntSort, smt.IntSort]:
		contextID := __gp_m20.contextID
		term := __gp_m20.term
		fast := __gp_m20.fast

		switch __gp_m21 := any(index).(type) {
		case intExprValue:
			indexContext := __gp_m21.contextID
			indexTerm := __gp_m21.term

			if contextID != indexContext {
				panic("gosmt: erased array/index context mismatch")
			}
			return selectIntArray(contextID, term, fast, indexTerm)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep StoreIntArray(0 c nat, array ArrayExpr[c, smt.IntSort, smt.IntSort], index IntExpr[c], value IntExpr[c]) ArrayExpr[c, smt.IntSort, smt.IntSort]
func StoreIntArray(array ArrayExpr[smt.IntSort, smt.IntSort], index IntExpr, value IntExpr) ArrayExpr[smt.IntSort, smt.IntSort] {
	switch __gp_m22 := any(array).(type) {
	case arrayExprValue[smt.IntSort, smt.IntSort]:
		contextID := __gp_m22.contextID
		term := __gp_m22.term
		fast := __gp_m22.fast

		switch __gp_m23 := any(index).(type) {
		case intExprValue:
			indexContext := __gp_m23.contextID
			indexTerm := __gp_m23.term

			switch __gp_m24 := any(value).(type) {
			case intExprValue:
				valueContext := __gp_m24.contextID
				valueTerm := __gp_m24.term

				if contextID != indexContext || contextID != valueContext {
					panic("gosmt: erased array store context mismatch")
				}
				return storeIntArray(contextID, term, fast, indexTerm, valueTerm)
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BitVecArrayConst(indexWidth nat, elementWidth nat, 0 c nat, context Context[c], name string, id int) BitVecArrayExpr[c, indexWidth, elementWidth]
func BitVecArrayConst(indexWidth int, elementWidth int, context Context, name string, id int) BitVecArrayExpr {
	switch __gp_m25 := any(context).(type) {
	case contextValue:
		contextID := __gp_m25.iD
		return fastBitVectorArraySymbol(contextID, int(indexWidth), int(elementWidth), id, name)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ConstBitVecArray(indexWidth nat, 0 c nat, 0 elementWidth nat, value BitVecExpr[c, elementWidth]) BitVecArrayExpr[c, indexWidth, elementWidth]
func ConstBitVecArray(indexWidth int, value BitVecExpr) BitVecArrayExpr {
	switch __gp_m26 := any(value).(type) {
	case bitVecExprValue:
		contextID := __gp_m26.contextID
		term := __gp_m26.term
		fast := __gp_m26.fast
		return bitVecArrayExprValue{contextID: contextID, term: smt.ConstArray[smt.BitVecSort, smt.BitVecSort](materializeBitVector(term, fast)), fast: bitVecArrayFast{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep SelectBitVecArray(0 c nat, 0 indexWidth nat, 0 elementWidth nat, array BitVecArrayExpr[c, indexWidth, elementWidth], index BitVecExpr[c, indexWidth]) BitVecExpr[c, elementWidth]
func SelectBitVecArray(array BitVecArrayExpr, index BitVecExpr) BitVecExpr {
	switch __gp_m27 := any(array).(type) {
	case bitVecArrayExprValue:
		contextID := __gp_m27.contextID
		term := __gp_m27.term
		arrayFast := __gp_m27.fast

		switch __gp_m28 := any(index).(type) {
		case bitVecExprValue:
			indexContext := __gp_m28.contextID
			indexTerm := __gp_m28.term
			indexFast := __gp_m28.fast

			if contextID != indexContext {
				panic("gosmt: erased bit-vector array/index context mismatch")
			}
			if value, width, ok := selectFastBitVectorArray(arrayFast, indexFast); ok {
				return fastBitVectorValue(contextID, width, value)
			}
			if value, ok := selectSymbolicBitVectorArray(contextID, arrayFast, indexFast); ok {
				return value
			}
			return bitVecExprValue{contextID: contextID, term: smt.Select(materializeBitVectorArray(term, arrayFast), materializeBitVector(indexTerm, indexFast)), fast: bitVectorFast{}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep StoreBitVecArray(0 c nat, 0 indexWidth nat, 0 elementWidth nat, array BitVecArrayExpr[c, indexWidth, elementWidth], index BitVecExpr[c, indexWidth], value BitVecExpr[c, elementWidth]) BitVecArrayExpr[c, indexWidth, elementWidth]
func StoreBitVecArray(array BitVecArrayExpr, index BitVecExpr, value BitVecExpr) BitVecArrayExpr {
	switch __gp_m29 := any(array).(type) {
	case bitVecArrayExprValue:
		contextID := __gp_m29.contextID
		term := __gp_m29.term
		arrayFast := __gp_m29.fast

		switch __gp_m30 := any(index).(type) {
		case bitVecExprValue:
			indexContext := __gp_m30.contextID
			indexTerm := __gp_m30.term
			indexFast := __gp_m30.fast

			switch __gp_m31 := any(value).(type) {
			case bitVecExprValue:
				valueContext := __gp_m31.contextID
				valueTerm := __gp_m31.term
				valueFast := __gp_m31.fast

				if contextID != indexContext || contextID != valueContext {
					panic("gosmt: erased bit-vector array store context mismatch")
				}
				if stored, ok := storeFastBitVectorArray(arrayFast, indexFast, valueFast); ok {
					return bitVecArrayExprValue{contextID: contextID, term: term, fast: stored}
				}
				return bitVecArrayExprValue{contextID: contextID, term: smt.Store(materializeBitVectorArray(term, arrayFast), materializeBitVector(indexTerm, indexFast), materializeBitVector(valueTerm, valueFast)), fast: bitVecArrayFast{}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EqBitVecArray(0 c nat, 0 indexWidth nat, 0 elementWidth nat, left BitVecArrayExpr[c, indexWidth, elementWidth], right BitVecArrayExpr[c, indexWidth, elementWidth]) BoolExpr[c]
func EqBitVecArray(left BitVecArrayExpr, right BitVecArrayExpr) BoolExpr {
	switch __gp_m32 := any(left).(type) {
	case bitVecArrayExprValue:
		contextID := __gp_m32.contextID
		leftTerm := __gp_m32.term
		leftFast := __gp_m32.fast

		switch __gp_m33 := any(right).(type) {
		case bitVecArrayExprValue:
			rightContext := __gp_m33.contextID
			rightTerm := __gp_m33.term
			rightFast := __gp_m33.fast

			if contextID != rightContext {
				panic("gosmt: erased bit-vector array context mismatch")
			}
			return fastBooleanAtom(contextID, smt.Equal{Left: materializeBitVectorArray(leftTerm, leftFast), Right: materializeBitVectorArray(rightTerm, rightFast)})
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep NotBitVec(0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, width]
func NotBitVec(value BitVecExpr) BitVecExpr {
	return fastNotBitVector(value)
}

//goplus:dep AndBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func AndBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return fastAndBitVector(left, right)
}

//goplus:dep OrBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func OrBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 2)
}

//goplus:dep XorBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func XorBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 3)
}

//goplus:dep AddBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func AddBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 4)
}

//goplus:dep SubBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func SubBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 5)
}

//goplus:dep MulBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func MulBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 6)
}

//goplus:dep ShlBitVec(0 c nat, 0 width nat, value BitVecExpr[c, width], amount BitVecExpr[c, width]) BitVecExpr[c, width]
func ShlBitVec(value BitVecExpr, amount BitVecExpr) BitVecExpr {
	return binaryBitVector(value, amount, 7)
}

//goplus:dep LshrBitVec(0 c nat, 0 width nat, value BitVecExpr[c, width], amount BitVecExpr[c, width]) BitVecExpr[c, width]
func LshrBitVec(value BitVecExpr, amount BitVecExpr) BitVecExpr {
	return binaryBitVector(value, amount, 8)
}

//goplus:dep AshrBitVec(0 c nat, 0 width nat, value BitVecExpr[c, width], amount BitVecExpr[c, width]) BitVecExpr[c, width]
func AshrBitVec(value BitVecExpr, amount BitVecExpr) BitVecExpr {
	return binaryBitVector(value, amount, 9)
}

//goplus:dep UdivBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func UdivBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 10)
}

//goplus:dep UremBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func UremBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 11)
}

//goplus:dep SdivBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func SdivBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 12)
}

//goplus:dep SremBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BitVecExpr[c, width]
func SremBitVec(left BitVecExpr, right BitVecExpr) BitVecExpr {
	return binaryBitVector(left, right, 13)
}

//goplus:dep UaddOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func UaddOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 1)
}

//goplus:dep SaddOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func SaddOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 2)
}

//goplus:dep UsubOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func UsubOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 3)
}

//goplus:dep SsubOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func SsubOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 4)
}

//goplus:dep UmulOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func UmulOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 5)
}

//goplus:dep SmulOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func SmulOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 6)
}

//goplus:dep SdivOverflowBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func SdivOverflowBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return overflowBitVector(left, right, 7)
}

//goplus:dep NegOverflowBitVec(0 c nat, 0 width nat, value BitVecExpr[c, width]) BoolExpr[c]
func NegOverflowBitVec(value BitVecExpr) BoolExpr {
	return negOverflowBitVector(value)
}

//goplus:dep ConcatBitVec(firstWidth nat, secondWidth nat, 0 c nat, first BitVecExpr[c, firstWidth], second BitVecExpr[c, secondWidth]) BitVecExpr[c, firstWidth+secondWidth]
func ConcatBitVec(firstWidth int, secondWidth int, first BitVecExpr, second BitVecExpr) BitVecExpr {
	return concatBitVector(int(firstWidth), int(secondWidth), first, second)
}

//goplus:dep ExtractBitVec(high nat, low nat, 0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, high-low+1]
func ExtractBitVec(high int, low int, value BitVecExpr) BitVecExpr {
	return extractBitVector(int(high), int(low), value)
}

//goplus:dep ZeroExtendBitVec(additional nat, 0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, width+additional]
func ZeroExtendBitVec(additional int, value BitVecExpr) BitVecExpr {
	return extendBitVector(int(additional), value, false)
}

//goplus:dep SignExtendBitVec(additional nat, 0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, width+additional]
func SignExtendBitVec(additional int, value BitVecExpr) BitVecExpr {
	return extendBitVector(int(additional), value, true)
}

//goplus:dep RotateLeftBitVec(amount nat, 0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, width]
func RotateLeftBitVec(amount int, value BitVecExpr) BitVecExpr {
	return rotateBitVector(int(amount), value, true)
}

//goplus:dep RotateRightBitVec(amount nat, 0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, width]
func RotateRightBitVec(amount int, value BitVecExpr) BitVecExpr {
	return rotateBitVector(int(amount), value, false)
}

//goplus:dep RepeatBitVec(count nat, 0 c nat, 0 width nat, value BitVecExpr[c, width]) BitVecExpr[c, width*count]
func RepeatBitVec(count int, value BitVecExpr) BitVecExpr {
	return repeatBitVector(int(count), value)
}

//goplus:dep EqBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func EqBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return fastEqBitVector(left, right)
}

//goplus:dep UltBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func UltBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return fastOrderBitVector(left, right, 1)
}

//goplus:dep UleBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func UleBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return fastOrderBitVector(left, right, 2)
}

//goplus:dep SltBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func SltBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return fastOrderBitVector(left, right, 3)
}

//goplus:dep SleBitVec(0 c nat, 0 width nat, left BitVecExpr[c, width], right BitVecExpr[c, width]) BoolExpr[c]
func SleBitVec(left BitVecExpr, right BitVecExpr) BoolExpr {
	return fastOrderBitVector(left, right, 4)
}

//goplus:dep ModelBitVec(0 c nat, 0 a nat, 0 width nat, model Model[c, a], term BitVecExpr[c, width]) (smt.BitVectorValue, bool)
func ModelBitVec(model Model, term BitVecExpr) (smt.BitVectorValue, bool) {
	switch __gp_m34 := any(model).(type) {
	case modelValue:
		contextID := __gp_m34.contextID
		core := __gp_m34.core

		switch __gp_m35 := any(term).(type) {
		case bitVecExprValue:
			termContext := __gp_m35.contextID
			value := __gp_m35.term
			fast := __gp_m35.fast

			if contextID != termContext {
				panic("gosmt: erased bit-vector model context mismatch")
			}
			return smt.BitVecModelValue(core, materializeBitVector(value, fast))
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep DeclareRealFunction(0 c nat, context Context[c], name string, id int) RealFunc[c]
func DeclareRealFunction(context Context, name string, id int) RealFunc {
	switch __gp_m36 := any(context).(type) {
	case contextValue:
		contextID := __gp_m36.iD
		return fastRealFunction(contextID, id, name)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ApplyRealFunction(0 c nat, function RealFunc[c], argument RealExpr[c]) RealExpr[c]
func ApplyRealFunction(function RealFunc, argument RealExpr) RealExpr {
	return applyRealFunction(function, argument)
}

//goplus:dep DeclareRealBinary(0 c nat, context Context[c], name string, id int) RealBinaryFunc[c]
func DeclareRealBinary(context Context, name string, id int) RealBinaryFunc {
	switch __gp_m37 := any(context).(type) {
	case contextValue:
		contextID := __gp_m37.iD
		return fastRealBinaryFunction(contextID, id, name)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ApplyRealBinary(0 c nat, function RealBinaryFunc[c], first RealExpr[c], second RealExpr[c]) RealExpr[c]
func ApplyRealBinary(function RealBinaryFunc, first RealExpr, second RealExpr) RealExpr {
	return applyRealBinaryFunction(function, first, second)
}

//goplus:dep DeclareBitVecFunction(domainWidth nat, rangeWidth nat, 0 c nat, context Context[c], name string, id int) BitVecFunc[c, domainWidth, rangeWidth]
func DeclareBitVecFunction(domainWidth int, rangeWidth int, context Context, name string, id int) BitVecFunc {
	switch __gp_m38 := any(context).(type) {
	case contextValue:
		contextID := __gp_m38.iD
		return bitVecFuncValue{contextID: contextID, function: smt.DeclareBitVecUnaryFunction(domainWidth, rangeWidth, id, name)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ApplyBitVecFunction(0 c nat, 0 domainWidth nat, 0 rangeWidth nat, function BitVecFunc[c, domainWidth, rangeWidth], argument BitVecExpr[c, domainWidth]) BitVecExpr[c, rangeWidth]
func ApplyBitVecFunction(function BitVecFunc, argument BitVecExpr) BitVecExpr {
	switch __gp_m39 := any(function).(type) {
	case bitVecFuncValue:
		contextID := __gp_m39.contextID
		core := __gp_m39.function

		switch any(argument).(type) {
		case bitVecExprValue:

			return applyBitVectorFunction(contextID, core, argument)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep DeclareBitVecBinary(firstWidth nat, secondWidth nat, rangeWidth nat, 0 c nat, context Context[c], name string, id int) BitVecBinaryFunc[c, firstWidth, secondWidth, rangeWidth]
func DeclareBitVecBinary(firstWidth int, secondWidth int, rangeWidth int, context Context, name string, id int) BitVecBinaryFunc {
	switch __gp_m41 := any(context).(type) {
	case contextValue:
		contextID := __gp_m41.iD
		return bitVecBinaryFuncValue{contextID: contextID, function: smt.DeclareBitVecBinaryFunction(firstWidth, secondWidth, rangeWidth, id, name)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ApplyBitVecBinary(0 c nat, 0 firstWidth nat, 0 secondWidth nat, 0 rangeWidth nat, function BitVecBinaryFunc[c, firstWidth, secondWidth, rangeWidth], first BitVecExpr[c, firstWidth], second BitVecExpr[c, secondWidth]) BitVecExpr[c, rangeWidth]
func ApplyBitVecBinary(function BitVecBinaryFunc, first BitVecExpr, second BitVecExpr) BitVecExpr {
	switch __gp_m42 := any(function).(type) {
	case bitVecBinaryFuncValue:
		contextID := __gp_m42.contextID
		core := __gp_m42.function

		switch __gp_m43 := any(first).(type) {
		case bitVecExprValue:
			firstContext := __gp_m43.contextID
			firstTerm := __gp_m43.term
			firstFast := __gp_m43.fast

			switch __gp_m44 := any(second).(type) {
			case bitVecExprValue:
				secondContext := __gp_m44.contextID
				secondTerm := __gp_m44.term
				secondFast := __gp_m44.fast

				if contextID != firstContext || contextID != secondContext {
					panic("gosmt: erased binary bit-vector function context mismatch")
				}
				return bitVecExprValue{contextID: contextID, term: smt.ApplyBitVecBinary(core, materializeBitVector(firstTerm, firstFast), materializeBitVector(secondTerm, secondFast)), fast: bitVectorFast{}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep UninterpretedConst(sort nat, 0 c nat, context Context[c], name string, id int) UninterpretedExpr[c, sort]
func UninterpretedConst(sort int, context Context, name string, id int) UninterpretedExpr {
	switch __gp_m45 := any(context).(type) {
	case contextValue:
		contextID := __gp_m45.iD
		return uninterpretedExprValue{contextID: contextID, term: smt.UninterpretedConstant(sort, id, name)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep DeclareUnary(domain nat, codomain nat, 0 c nat, context Context[c], name string, id int) UnaryFunc[c, domain, codomain]
func DeclareUnary(domain int, codomain int, context Context, name string, id int) UnaryFunc {
	switch __gp_m46 := any(context).(type) {
	case contextValue:
		contextID := __gp_m46.iD
		return unaryFuncValue{contextID: contextID, function: smt.DeclareUnaryFunction(domain, codomain, id, name)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep DeclareBinary(first nat, second nat, codomain nat, 0 c nat, context Context[c], name string, id int) BinaryFunc[c, first, second, codomain]
func DeclareBinary(first int, second int, codomain int, context Context, name string, id int) BinaryFunc {
	switch __gp_m47 := any(context).(type) {
	case contextValue:
		contextID := __gp_m47.iD
		return binaryFuncValue{contextID: contextID, function: smt.DeclareBinaryFunction(first, second, codomain, id, name)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ApplyUninterpreted(0 c nat, 0 domain nat, 0 codomain nat, function UnaryFunc[c, domain, codomain], argument UninterpretedExpr[c, domain]) UninterpretedExpr[c, codomain]
func ApplyUninterpreted(function UnaryFunc, argument UninterpretedExpr) UninterpretedExpr {
	switch __gp_m48 := any(function).(type) {
	case unaryFuncValue:
		contextID := __gp_m48.contextID
		core := __gp_m48.function

		switch __gp_m49 := any(argument).(type) {
		case uninterpretedExprValue:
			argumentContext := __gp_m49.contextID
			term := __gp_m49.term

			if contextID != argumentContext {
				panic("gosmt: erased uninterpreted application context mismatch")
			}
			return uninterpretedExprValue{contextID: contextID, term: smt.ApplyUnary(core, term)}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep ApplyBinaryUninterpreted(0 c nat, 0 first nat, 0 second nat, 0 codomain nat, function BinaryFunc[c, first, second, codomain], left UninterpretedExpr[c, first], right UninterpretedExpr[c, second]) UninterpretedExpr[c, codomain]
func ApplyBinaryUninterpreted(function BinaryFunc, left UninterpretedExpr, right UninterpretedExpr) UninterpretedExpr {
	switch __gp_m50 := any(function).(type) {
	case binaryFuncValue:
		contextID := __gp_m50.contextID
		core := __gp_m50.function

		switch __gp_m51 := any(left).(type) {
		case uninterpretedExprValue:
			leftContext := __gp_m51.contextID
			leftTerm := __gp_m51.term

			switch __gp_m52 := any(right).(type) {
			case uninterpretedExprValue:
				rightContext := __gp_m52.contextID
				rightTerm := __gp_m52.term

				if contextID != leftContext || contextID != rightContext {
					panic("gosmt: erased binary application context mismatch")
				}
				return uninterpretedExprValue{contextID: contextID, term: smt.ApplyBinary(core, leftTerm, rightTerm)}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EqUninterpreted(0 c nat, 0 sort nat, left UninterpretedExpr[c, sort], right UninterpretedExpr[c, sort]) BoolExpr[c]
func EqUninterpreted(left UninterpretedExpr, right UninterpretedExpr) BoolExpr {
	switch __gp_m53 := any(left).(type) {
	case uninterpretedExprValue:
		contextID := __gp_m53.contextID
		leftTerm := __gp_m53.term

		switch __gp_m54 := any(right).(type) {
		case uninterpretedExprValue:
			rightContext := __gp_m54.contextID
			rightTerm := __gp_m54.term

			if contextID != rightContext {
				panic("gosmt: erased uninterpreted equality context mismatch")
			}
			return fastBooleanAtom(contextID, smt.Equal{Left: leftTerm, Right: rightTerm})
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Not(0 c nat, value BoolExpr[c]) BoolExpr[c]
func Not(value BoolExpr) BoolExpr {
	return fastNot(value)
}

//goplus:dep And(0 c nat, values ...BoolExpr[c]) BoolExpr[c]
func And(values ...BoolExpr) BoolExpr {
	return fastAnd(values)
}

//goplus:dep Or(0 c nat, values ...BoolExpr[c]) BoolExpr[c]
func Or(values ...BoolExpr) BoolExpr {
	return fastOr(values)
}

//goplus:dep Add(0 c nat, values ...IntExpr[c]) IntExpr[c]
func Add(values ...IntExpr) IntExpr {
	context, terms := integerTerms(values)
	return intExprValue{contextID: context, term: smt.Add{Values: terms}}
}

//goplus:dep Sub(0 c nat, left IntExpr[c], right IntExpr[c]) IntExpr[c]
func Sub(left IntExpr, right IntExpr) IntExpr {
	return subtractInteger(left, right)
}

//goplus:dep Le(0 c nat, left IntExpr[c], right IntExpr[c]) BoolExpr[c]
func Le(left IntExpr, right IntExpr) BoolExpr {
	return compareInteger(left, right, false)
}

//goplus:dep Lt(0 c nat, left IntExpr[c], right IntExpr[c]) BoolExpr[c]
func Lt(left IntExpr, right IntExpr) BoolExpr {
	return compareInteger(left, right, true)
}

//goplus:dep EqInt(0 c nat, left IntExpr[c], right IntExpr[c]) BoolExpr[c]
func EqInt(left IntExpr, right IntExpr) BoolExpr {
	return fastEqInteger(left, right)
}

//goplus:dep AddReal(0 c nat, values ...RealExpr[c]) RealExpr[c]
func AddReal(values ...RealExpr) RealExpr {
	return fastAddReal(values)
}

//goplus:dep SubReal(0 c nat, left RealExpr[c], right RealExpr[c]) RealExpr[c]
func SubReal(left RealExpr, right RealExpr) RealExpr {
	return fastSubReal(left, right)
}

//goplus:dep ScaleReal(0 c nat, coefficient smt.Rational, value RealExpr[c]) RealExpr[c]
func ScaleReal(coefficient smt.Rational, value RealExpr) RealExpr {
	return fastScaleReal(coefficient, value)
}

//goplus:dep LeReal(0 c nat, left RealExpr[c], right RealExpr[c]) BoolExpr[c]
func LeReal(left RealExpr, right RealExpr) BoolExpr {
	return fastRealRelation(left, right, false)
}

//goplus:dep LtReal(0 c nat, left RealExpr[c], right RealExpr[c]) BoolExpr[c]
func LtReal(left RealExpr, right RealExpr) BoolExpr {
	return fastRealRelation(left, right, true)
}

//goplus:dep EqReal(0 c nat, left RealExpr[c], right RealExpr[c]) BoolExpr[c]
func EqReal(left RealExpr, right RealExpr) BoolExpr {
	return fastEqReal(left, right)
}

//goplus:dep NewSolver(0 c nat, context Context[c]) Solver[c, 0, 0]
func NewSolver(context Context) Solver {
	switch __gp_m55 := any(context).(type) {
	case contextValue:
		contextID := __gp_m55.iD
		return solverValue{contextID: contextID, core: smt.New()}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Assert(assertion nat, 0 c nat, 0 a nat, 0 d nat, solver Solver[c, a, d], formula BoolExpr[c]) Solver[c, smt.ContextID(a, assertion), d]
func Assert(assertion int, solver Solver, formula BoolExpr) Solver {
	switch __gp_m56 := any(solver).(type) {
	case solverValue:
		context := __gp_m56.contextID
		core := __gp_m56.core

		switch __gp_m57 := any(formula).(type) {
		case boolExprValue:
			formulaContext := __gp_m57.contextID
			term := __gp_m57.term
			fast := __gp_m57.fast

			if context != formulaContext {
				panic("gosmt: erased context mismatch")
			}
			return solverValue{contextID: context, core: smt.Assert(assertion, core, materializeBoolean(term, fast))}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Check(0 c nat, 0 a nat, 0 d nat, solver Solver[c, a, d]) Result[c, a]
func Check(solver Solver) Result {
	switch __gp_m58 := any(solver).(type) {
	case solverValue:
		context := __gp_m58.contextID
		core := __gp_m58.core

		return cachedCheckResult(context, core)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep CheckAssuming(0 c nat, 0 a nat, 0 d nat, solver Solver[c, a, d], assumptions ...BoolExpr[c]) AssumptionResult[c, a]
func CheckAssuming(solver Solver, assumptions ...BoolExpr) AssumptionResult {
	switch __gp_m59 := any(solver).(type) {
	case solverValue:
		context := __gp_m59.contextID
		core := __gp_m59.core

		terms := assumptionTerms(context, assumptions)
		switch __gp_m60 := any(smt.CheckAssuming(core, terms...)).(type) {
		case smt.AssumptionsSatisfiable:
			model := __gp_m60.Value
			return AssumptionSat{Value: modelValue{contextID: context, core: model}}
		case smt.AssumptionsUnsatisfiable:
			proof := __gp_m60.Value
			indices := __gp_m60.Indices
			return AssumptionUnsat{Context: contextValue{iD: context}, Proof: proof, Indices: indices}
		case smt.AssumptionsUnknown:
			proof := __gp_m60.Context
			reason := __gp_m60.Reason
			return AssumptionUnknown{Context: contextValue{iD: context}, Proof: proof, Reason: reason}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EvalBool(0 c nat, 0 a nat, model Model[c, a], expression BoolExpr[c]) (bool, bool)
func EvalBool(model Model, expression BoolExpr) (bool, bool) {
	switch __gp_m61 := any(model).(type) {
	case modelValue:
		context := __gp_m61.contextID
		core := __gp_m61.core

		switch __gp_m62 := any(expression).(type) {
		case boolExprValue:
			expressionContext := __gp_m62.contextID
			term := __gp_m62.term
			fast := __gp_m62.fast

			if context != expressionContext {
				panic("gosmt: erased model/expression context mismatch")
			}
			return smt.BoolValue(core, materializeBoolean(term, fast))
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EvalInt(0 c nat, 0 a nat, model Model[c, a], expression IntExpr[c]) (int64, bool)
func EvalInt(model Model, expression IntExpr) (int64, bool) {
	switch __gp_m63 := any(model).(type) {
	case modelValue:
		context := __gp_m63.contextID
		core := __gp_m63.core

		switch __gp_m64 := any(expression).(type) {
		case intExprValue:
			expressionContext := __gp_m64.contextID
			term := __gp_m64.term

			if context != expressionContext {
				panic("gosmt: erased model/expression context mismatch")
			}
			return smt.IntValue(core, term)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EvalIntExact(0 c nat, 0 a nat, model Model[c, a], expression IntExpr[c]) (smt.IntegerValue, bool)
func EvalIntExact(model Model, expression IntExpr) (smt.IntegerValue, bool) {
	switch __gp_m65 := any(model).(type) {
	case modelValue:
		context := __gp_m65.contextID
		core := __gp_m65.core

		switch __gp_m66 := any(expression).(type) {
		case intExprValue:
			expressionContext := __gp_m66.contextID
			term := __gp_m66.term

			if context != expressionContext {
				panic("gosmt: erased model/expression context mismatch")
			}
			return smt.IntegerModelValue(core, term)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EvalIntArray(0 c nat, 0 a nat, model Model[c, a], array ArrayExpr[c, smt.IntSort, smt.IntSort], index smt.IntegerValue) (smt.IntegerValue, bool)
func EvalIntArray(model Model, array ArrayExpr[smt.IntSort, smt.IntSort], index smt.IntegerValue) (smt.IntegerValue, bool) {
	switch __gp_m67 := any(model).(type) {
	case modelValue:
		context := __gp_m67.contextID
		core := __gp_m67.core

		switch __gp_m68 := any(array).(type) {
		case arrayExprValue[smt.IntSort, smt.IntSort]:
			arrayContext := __gp_m68.contextID
			term := __gp_m68.term
			fast := __gp_m68.fast

			if context != arrayContext {
				panic("gosmt: erased model/array context mismatch")
			}
			return smt.IntegerArrayValue(core, materializeArray(term, fast), index)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep EvalReal(0 c nat, 0 a nat, model Model[c, a], expression RealExpr[c]) (smt.Rational, bool)
func EvalReal(model Model, expression RealExpr) (smt.Rational, bool) {
	switch __gp_m69 := any(model).(type) {
	case modelValue:
		context := __gp_m69.contextID
		core := __gp_m69.core

		switch __gp_m70 := any(expression).(type) {
		case realExprValue:
			expressionContext := __gp_m70.contextID
			term := __gp_m70.term
			fast := __gp_m70.fast

			if context != expressionContext {
				panic("gosmt: erased model/expression context mismatch")
			}
			return smt.RealValue(core, materializeReal(term, fast))
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
